version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - C:/Users/jugalb/.docker/config.json:/config.json
    command: --debug
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
      - WATCHTOWER_AUTH_FILE=/config.json
      - WATCHTOWER_POLL_INTERVAL=120
      - WATCHTOWER_TRACE=true 
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 8080:8080
    networks:
      - wt-app

  mongo:
    image: mongo:4.4.19
    restart: unless-stopped
    ports:
      - 27025:27017
    networks:
      - wt-app
    volumes:
      - db:/data/db
    command: mongod --bind_ip_all --port 27017
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5

  server:
    image: jugalb/wt-apps-server:latest  # Use the 'latest' tag
    restart: unless-stopped
    environment:
      - PORT=8000
      - WATCHTOWER_URL=http://localhost:8080
      - MONGODB_URL=mongodb://mongo:27017/authApp
    ports:
      - 8000:8000
    networks:
      - wt-app

  client:
    image: jugalb/wt-apps-client:latest  # Use the 'latest' tag
    restart: unless-stopped
    environment:  
      - REACT_APP_API_URL=http://127.0.0.1:8000/api
    ports: 
      - 3000:3000
    networks:
      - wt-app

volumes:
  db:

networks:
  wt-app:
    driver: bridge
