version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - C:/Users/jugalb/.docker/config.json:/config.json
    command: --debug --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
      - WATCHTOWER_AUTH_FILE=/config.json
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8080:8080
    networks:
      - wt-app

  mongo:
    image: mongo:4.4.19
    restart: unless-stopped
    ports:
      - 27025:27017
    networks:
      - wt-app
    volumes:
      - db:/data/db
    command: mongod --bind_ip_all --port 27017
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5

  server:
    depends_on:
      - mongo
    build: 
      context: server/
    restart: unless-stopped
    environment:  
      - PORT=8000
      - MONGODB_URL=mongodb://mongo:27017/authApp
      - WATCHTOWER_API_URL=http://watchtower:8080/v1/update
      - WATCHTOWER_API_TOKEN=mytoken
    ports:
      - 8000:8000
    networks:
      - wt-app
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  client:
    depends_on:
      - server
    build:
      context: client/
      args:
        API_URL: http://127.0.0.1:8000/api
    restart: unless-stopped
    ports: 
      - 3000:3000
    networks:
      - wt-app
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  db:

networks:
  wt-app:
    driver: bridge
