name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  DOCKER_USERNAME: jugalb
  DOCKER_SERVER_REPO: wt-apps-server
  DOCKER_CLIENT_REPO: wt-apps-client

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKERPW }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

    - name: Determine version numbers
      id: get_versions
      run: |
        # Fetch the list of tags for the server and client
        SERVER_TAGS=$(curl -s "https://hub.docker.com/v2/repositories/jugalb/${{ env.DOCKER_SERVER_REPO }}/tags?page_size=100" | jq -r '.results[].name')
        CLIENT_TAGS=$(curl -s "https://hub.docker.com/v2/repositories/jugalb/${{ env.DOCKER_CLIENT_REPO }}/tags?page_size=100" | jq -r '.results[].name')

        # Get the highest version number from existing tags (or default to 0 if no tags exist)
        SERVER_LATEST_TAG=$(echo "$SERVER_TAGS" | grep -Eo 'v[0-9]+' | sort -V | tail -n 1 || echo "v0")
        CLIENT_LATEST_TAG=$(echo "$CLIENT_TAGS" | grep -Eo 'v[0-9]+' | sort -V | tail -n 1 || echo "v0")

        # Extract numeric parts of the version or default to 0
        SERVER_VERSION=$(echo $SERVER_LATEST_TAG | grep -oP '\d+' || echo "0")
        CLIENT_VERSION=$(echo $CLIENT_LATEST_TAG | grep -oP '\d+' || echo "0")

        # Increment the versions
        SERVER_NEW_VERSION=$((SERVER_VERSION + 1))
        CLIENT_NEW_VERSION=$((CLIENT_VERSION + 1))

        # Set new version numbers as environment variables
        echo "SERVER_NEW_VERSION=v${SERVER_NEW_VERSION}" >> $GITHUB_ENV
        echo "CLIENT_NEW_VERSION=v${CLIENT_NEW_VERSION}" >> $GITHUB_ENV

    - name: Log version information
      run: |
        echo "New server version: $SERVER_NEW_VERSION"
        echo "New client version: $CLIENT_NEW_VERSION"

    - name: Build and push server Docker image
      working-directory: ./server
      run: |
        # Build images with both versioned and latest tags
        docker build -t jugalb/${{ env.DOCKER_SERVER_REPO }}:${{ env.SERVER_NEW_VERSION }} .
        docker build -t jugalb/${{ env.DOCKER_SERVER_REPO }}:latest .

        # Push both images
        docker push jugalb/${{ env.DOCKER_SERVER_REPO }}:${{ env.SERVER_NEW_VERSION }}
        docker push jugalb/${{ env.DOCKER_SERVER_REPO }}:latest

    - name: Build and push client Docker image
      working-directory: ./client
      run: |
        # Build images with both versioned and latest tags
        docker build -t jugalb/${{ env.DOCKER_CLIENT_REPO }}:${{ env.CLIENT_NEW_VERSION }} .
        docker build -t jugalb/${{ env.DOCKER_CLIENT_REPO }}:latest .

        # Push both images
        docker push jugalb/${{ env.DOCKER_CLIENT_REPO }}:${{ env.CLIENT_NEW_VERSION }}
        docker push jugalb/${{ env.DOCKER_CLIENT_REPO }}:latest
